In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
x = pd.read_csv("../data/somas within LC mesh 250630.csv")

In [5]:
x

,0,1,2,10,20,30,40,50,60,70,80,90,67
0,9805.1909,5907.0996,4330.8163,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,10058.1685,5220.5902,4474.7315,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,10094.2631,5153.0540,4674.3972,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,10178.2278,5072.3241,4617.7922,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
4,9709.7926,5022.2970,3873.3075,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,10307.7860,4087.2135,4826.8439,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
104,9963.9391,4052.6924,4917.9727,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
105,10130.3109,4011.5415,4777.1360,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
106,9981.7118,3798.5471,4966.5825,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
107,10097.9499,3763.3747,5072.7667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [41]:
df = x.sum()[3:].to_frame(name="Cells in Mesh")
df["Percent in Mesh"] = (df["Cells in Mesh"] / 108) * 100
df["Percent in Mesh"] = df["Percent in Mesh"].astype(int)
df["Cells in Mesh"] = df["Cells in Mesh"].astype(int)
df = df.T
df.index.name = "Mesh Percentile"
df = df.loc[["Percent in Mesh","Cells in Mesh"]]
df

                 10  20  30  40  50  60  70  80  90  67
Mesh Percentile
Percent in Mesh  26  33  39  48  52  59  74  81  91  69
Cells in Mesh    29  36  43  52  57  64  80  88  99  75